services:
  - type: web
    name: news-scraper
    env: python
    buildCommand: poetry install
    startCommand: poetry run python scheduler.py
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://trung7cyv:Pwrl2KClurSIANRy@cluster0.wwa6we5.mongodb.net/?retryWrites=true&w=majority
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: /
    autoDeploy: true 